### ISSUE TITLE
edge-simplified-installer compose fails due to default size

### ISSUE THREAD

**Issue by jce-redhat** [redhat-cop/infra.osbuild#108]
the following task fails in an non-obvious way because `infra.osbuild.start_compose` has a default image size of 8MiB:

```
- name: Start simplified installer compose
  infra.osbuild.start_compose:
    blueprint: SimplifiedInstaller
    compose_type: edge-simplified-installer
    ostree_url: http://localhost:8000/repo/
```

if i explicitly add the argument `size: 0` the task succeeds.  reading the composer-cli-compose-start(1) man page, it suggests that the CLI default for size is 0.  should the default size argument for `infra.osbuild.start_compose` be set to 0?  composer seems to do the right thing if this is the case.
