### ISSUE TITLE
Builder role - Anaconda gets stuck on no root info

### ISSUE THREAD

**Issue by zjpeterson** [redhat-cop/infra.osbuild#124]
When kickstarting from an image built by the infra.osbuild.builder role, anaconda (RHEL 9.1) stops to complain that it doesn't have all the information it needs. You can make the install proceed by filling out a root password interactively. However, this stop in the process makes it unsuitable for zero-touch provisioning.

I'm currently working around it by adding the following to a playbook resembling https://github.com/redhat-cop/infra.osbuild/blob/main/playbooks/osbuild_builder.yml
```yaml
  vars:
    builder_root_password: ansible

  post_tasks:
    - name: Hash root password
      ansible.builtin.command:
        cmd: openssl passwd -6 '{{ builder_root_password }}'
      register: rootpw

    - name: Add root password to kickstart
      ansible.builtin.lineinfile:
        line: rootpw --iscrypted {{ rootpw.stdout }}
        path: /var/www/html/{{ builder_blueprint_name }}/kickstart.ks
        insertbefore: ^sshkey*
```
