### ISSUE TITLE
build os image with custom repos fails

### ISSUE THREAD

**Issue by morvencao** [redhat-cop/infra.osbuild#154]
When I try to build os mage with role `infra.osbuild.builder` with custom repos:

```
builder_custom_repos:
      - name: EPEL8
        base_url: "https://dl.fedoraproject.org/pub/epel/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/Everything/x86_64/"
        type: yum-baseurl
        check_ssl: true
        check_gpg: false
      - name: microshift
        base_url: "file:///home/microshift/microshift-local/"
        type: yum-baseurl
        check_ssl: false
        check_gpg: false
      - name: microshift-deps
        base_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rpms/4.12-el8-beta/
        type: yum-baseurl
        check_ssl: true
        check_gpg: false
```

it always fails at compose phase:

```
TASK [infra.osbuild.builder : Start compose] *************************************************************************************************************************************
task path: /root/.ansible/collections/ansible_collections/infra/osbuild/roles/builder/tasks/main.yml:97
...
The full traceback is:
  File "/tmp/ansible_infra.osbuild.start_compose_payload_rpsj4wxv/ansible_infra.osbuild.start_compose_payload.zip/ansible_collections/infra/osbuild/plugins/module_utils/weldrapiv1.py", line 310, in post_compose
    headers={"Content-Type": "application/json"},
  File "/tmp/ansible_infra.osbuild.start_compose_payload_rpsj4wxv/ansible_infra.osbuild.start_compose_payload.zip/ansible/module_utils/urls.py", line 1557, in open
    r = urllib_request.urlopen(request, None, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_duplicate": true,
            "blueprint": "microshift",
            "compose_type": "edge-commit",
            "image_name": "",
            "ostree_parent": "",
            "ostree_ref": "",
            "ostree_url": "",
            "profile": "",
            "size": 0
        }
    },
    "msg": "OSBUILD COMPOSER ERROR: Internal Server Error"
}
```
