### ISSUE TITLE
Intermittent "Unable to determine state of build" errors

### ISSUE THREAD

**Issue by empovit** [redhat-cop/infra.osbuild#182]
Sometimes the Start compose task of `infra.osbuild.builder` fails with the following message:

```
TASK [infra.osbuild.builder : Start compose] **********************************************************************************************************
fatal: [osbuild]: FAILED! => {"changed": false, "msg": "Unable to determine state of build, check osbuild-composer system logs"}
```

There doesn't seem anything in the journal logs that could explain the problem. Just re-running the playbook is often successful.

As far as I can tell, the issue happens after the initial setup of a build server using `infra.osbuild.setup_server`, or after restarting the osbuild composer services. So probably verifying the status of the service(s) isn't enough and some additional health check is needed.

Seen on RHEL 9.2

**Comment by jjaswanson4** [comment]
This is probably related to Image Builder having to build its cache the first time you try to compose an image.

On slower systems, it takes a few minutes for this to be built, and while that's happening, the build isn't technically accepted or visible as a compose.

Probably could add a simple "wait" after attempting to submit a compose to allow the cache to be built, or more long term: see if the cache is built, if not wait for it to be built then go check for the compose.

**Comment by jjaswanson4** [comment]
Ok, here's an idea:

Restarting the service after the cache has been cleared triggers a rebuild of the cache, which creates a few processes:
```
[jswanson@josh-edge-device ~]$ ps aux | grep dnf-json | grep -v grep
_osbuil+   77519  8.4  0.7 581628 125416 ?       R    11:44   0:04 /usr/bin/python3 /usr/libexec/osbuild-composer/dnf-json
_osbuil+   77520  0.3  0.2 278388 41600 ?        S    11:44   0:00 /usr/bin/python3 /usr/libexec/osbuild-composer/dnf-json
_osbuil+   77521  0.3  0.2 278388 41392 ?        S    11:44   0:00 /usr/bin/python3 /usr/libexec/osbuild-composer/dnf-json
_osbuil+   77522  0.3  0.2 278388 41188 ?        S    11:44   0:00 /usr/bin/python3 /usr/libexec/osbuild-composer/dnf-json
_osbuil+   77523  0.3  0.2 278388 41960 ?        S    11:44   0:00 /usr/bin/python3 /usr/libexec/osbuild-composer/dnf-json
_osbuil+   77526  0.3  0.2 278388 41752 ?        S    11:44   0:00 /usr/bin/python3 /usr/libexec/osbuild-composer/dnf-json
_osbuil+   77527  0.3  0.2 278388 41408 ?        S    11:44   0:00 /usr/bin/python3 /usr/libexec/osbuild-composer/dnf-json
_osbuil+   77528  0.3  0.2 278388 41828 ?        S    11:44   0:00 /usr/bin/python3 /usr/libexec/osbuild-composer/dnf-json
```

An idea may be to check for this process(es), and if present, wait before attempting to submit a compose.

**Comment by maxamillion** [comment]
I'm conflicted on this. I do like the idea of not attempting the build until the cache is done building, but I don't like running that shell one-liner for various reasons. However, I don't see any other way to extract status of the cache rebuild from the ostree/ostree-composer system so we might be stuck with it.

**Comment by empovit** [comment]
I took another look at the [code](https://github.com/redhat-cop/infra.osbuild/blob/fc151395c10bb148e646c6b574cc39dab6aa5830/roles/setup_server/tasks/main.yaml#L104), and saw that it didn't include any meaningful validation of the osbuild service status.

```
- name: Enable Cockpit/Composer/Firewalld/Apache
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  loop:
    - osbuild-composer.socket
    - cockpit.socket
    - httpd.service
    - firewalld
```

Unfortunately, `ansible.builtin.systemd` is a bit peculiar in this regard - it will make sure the service is started, but not that it's become active.

As a first step, I'd suggest adding something along the lines of the following to the [builder role](https://github.com/redhat-cop/infra.osbuild/blob/fc151395c10bb148e646c6b574cc39dab6aa5830/roles/builder/tasks/main.yml#L38):

```
    - name: Check osbuild-composer status
      ansible.builtin.systemd:
        name: osbuild-composer
      register: builder_osbuild_composer_status

    - name: Report osbuild-composer status
      ansible.builtin.fail:
        msg: OSBuild Composer Service failed to start.
      when: builder_osbuild_composer_status.status.ActiveState != 'active'
```

Not sure if `osbuild-worker@1` also needs checking, but it probably won't hurt.

We had to do this in the [FDO collection](https://github.com/ansible-collections/community.fdo/blob/dd2d5031446dd26a1c97977b532a1bafa44b4399/roles/configure_rendezvous_server/tasks/main.yml#L14) for a similar reason, i.e. the FDO servers were rejecting requests because they weren't fully up after a systemd start/restart.
