### ISSUE TITLE
RHSM Repos Not Handled Correctly

### ISSUE THREAD

**Issue by jjaswanson4** [redhat-cop/infra.osbuild#194]
When running with additional RHSM repos, the collection does not appropriately handle enabling them:

```
TASK [infra.osbuild.builder : Get rhsm repos properties] *************************************************************************************************************************************************************************************************************************************************************************************
fatal: [edge-manager-local]: FAILED! => {"changed": false, "msg": "Could not find {'name': 'rhel-9-for-x86_64-rt-rpms'} in the files inside /etc/yum.repos.d/ directory. Error: <class 'Exception'>"}
```

Tested on:
```
(.venv) [jswanson@jswanson-fedora device-edge-workshops]$ ansible --version
ansible [core 2.14.1]
  config file = /home/jswanson/code/device-edge-workshops/ansible.cfg
  configured module search path = ['/home/jswanson/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jswanson/code/device-edge-workshops/.venv/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/jswanson/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jswanson/code/device-edge-workshops/.venv/bin/ansible
  python version = 3.10.11 (main, Apr  5 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/home/jswanson/code/device-edge-workshops/.venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

Target is EL9.2, and the system can enable the repo via SM:
```
sudo subscription-manager repos --enable=rhel-9-for-x86_64-rt-rpms
Repository 'rhel-9-for-x86_64-rt-rpms' is enabled for this system.
```

variables:
```yaml
    builder_compose_type: edge-commit
    builder_blueprint_name: rhde-rt-image
    builder_compose_pkgs:
      - vim-enhanced
      - git
      - nano
      - NetworkManager-wifi
      - podman
    builder_rhsm_repos:
      - name: rhel-9-for-x86_64-rt-rpms
    builder_compose_customizations:
      user:
        name: ansible
        password: "{{ admin_password }}"
        groups:
          - wheel
      kernel:
        name: kernel-rt
```
