### ISSUE TITLE
remove sshkey in testbuild.yml and replace with variable

### ISSUE THREAD

**Issue by chadmf** [redhat-cop/infra.osbuild#26]
##### SUMMARY
Please remove the hard coded ssh key in testbuild.yml and replace with a variable.
Example:
```
        customizations:
          user:
            name: "core"
            description: "test user"
            password: "openshift"
            key: "{{ ssh_key }}"
```
