### ISSUE TITLE
Setup_server does not cater for aarch64

### ISSUE THREAD

**Issue by hvanniek** [redhat-cop/infra.osbuild#282]
In roles/setup_server/tasks/main.yaml, the architecture is hardcoded:
```
    - name: Setup Repositories
      vars:
        rhc_repositories:
          - {name: "*", state: disabled}
          - {name: "rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms", state: enabled}
          - {name: "rhel-{{ ansible_distribution_major_version }}-for-x86_64-baseos-rpms", state: enabled}
```
Replace x86_64 with ```{{ ansible_architecture }}``` to fix this.

Still leaves a package rhc-worker-playbook missing in the aarch64 repo though.
