### ISSUE TITLE
No space left on device with VHD target, only with Ansible module

### ISSUE THREAD

**Issue by Procsiab** [redhat-cop/infra.osbuild#291]
I am reporting this since I cannot reproduce it from `composer-cli`, and from the metadata produced by the compose it seems that the custom size I set for the image artefact is respected, however: every compose that I run with the `infra.osbuild.start_compose` module and VHD target fails at the step `org.osbuild.copy` with the following error:

```
cp: error writing '/run/osbuild[...]': No space left on device
```

If I run the same compose from the CLI, it succeeds (I use the same parameters declared as the module's arguments).

I am using the `infra.osbuild` collection version `2.2.0`, on a `Fedora 38` system with `Python 3.9.16`
I attach the metadata and log files for both the succeeding job run from CLI and the failing one run from Ansible, and also the blueprint file and the command/task I used to run the respective composes.

**Successful CLI run**
```bash
composer-cli compose start datalab_general vhd datalab_general template_static/az_storage_account.toml --size 5120
```

**Failed Ansible run**
```yaml
hosts: localhost
tasks:
  - name: Start the compose job, with VHD target                                                       
    infra.osbuild.start_compose:                                                                       
      blueprint: "{{ blueprint_name }}"                                                                
      size: 5120                                                                                       
      profile: "{{ lookup('ansible.builtin.template', 'templates/' + storageprof_name + '.toml.j2') }}"
      image_name: "{{ blueprint_name }}_img"                                                           
      allow_duplicate: true  # not idempotent                                                          
      compose_type: 'vhd'                                                                              
      timeout: 150                                                                                     
    register: builder_compose_start_out 
```

[infra_osbuild_issue.zip](https://github.com/redhat-cop/infra.osbuild/files/12598632/infra_osbuild_issue.zip)
