### ISSUE TITLE
change start socket to restarted in builder/tasks/main.yml

### ISSUE THREAD

**Issue by chadmf** [redhat-cop/infra.osbuild#37]
##### SUMMARY
Sometimes the cockpit service fails and we need to make sure it is running before building images.
and results in:

```shell
TASK [osbuild.composer.builder : Push the blueprint into image builder] ********************************************************
fatal: [192.168.122.84]: FAILED! => {"changed": false, "msg": "Connection to osbuild-composer service failed, please ensure service is running"}
```

```yaml
- name: Enable Cockpit/Composer/Firewalld/Apache
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: cockpit.socket
```

This should be:

```yaml
- name: Enable Cockpit/Composer/Firewalld/Apache
  ansible.builtin.systemd:
    state: restarted
    enabled: yes
    name: cockpit.socket
```
##### ISSUE TYPE
- Bug Report
