### ISSUE TITLE
Bug - infra.osbuild.setup_server fails to detect Satellite installation correctly

### ISSUE THREAD

**Issue by timdenholm** [redhat-cop/infra.osbuild#449]
When running the `infra.osbuild.setup_server` role on a host that is joined to Satellite it's failing incorrectly despite successfully testing for the existence of `/etc/rhsm/ca/katello-server-ca.pem`.

Playbook:

```yaml
---
- name: "Install and configure osbuild"
  hosts: "osbuild"
  vars:
    setup_server_rhsatellite: true
    setup_server_rhsatellite_host: "satellite.xyz"
  tasks:
    - ansible.builtin.import_role:
        name: "infra.osbuild.setup_server"
```

Expected result:

```
TASK [infra.osbuild.setup_server : Check if Satellite installed] ***************
ok: [osbuild]

TASK [infra.osbuild.setup_server : Error message if Satellite is missing] ******
skipping: [osbuild]
```

Actual result:

```
TASK [infra.osbuild.setup_server : Check if Satellite installed] ***************
ok: [osbuild]

TASK [infra.osbuild.setup_server : Error message if Satellite is missing] ******
fatal: [osbuild] FAILED! => {"changed": false, "msg": "Satellite not found, please ensure Satellite is configured properly"}
```

The logic for the `Error message if Satellite is missing` task is incorrect.
